(in-package :back-end)

(defclass activity ()
  ((id :col-type integer :col-identity t :initarg :id :accessor id)
   (title :col-type string :initarg :title :accessor title)
   (subtitle :col-type string :initarg :subtitle :accessor subtitle)
   (sla :col-type integer :initarg :sla :accessor sla))
  (:metaclass dao-class)
  (:keys id)
  (:table-name activities))

(defclass card ()
  ((id :col-type integer :col-identity t :accessor id)
   (creation-date :col-name creationDate :col-type timestamp
		  :initarg :creation-date :accessor creation-date)
   (patient-id :col-name patientId :col-type integer :col-references ((patients id))
	       :initarg :patient-id :accessor patient-id)
   (activity-id :col-name activityId :col-type integer :col-references ((activities id))
		:initarg :activity-id :accessor activity-id)
   (health-insurance-id :col-name healthInsuranceId :col-type integer :col-references ((healthInsurances id))
			:initarg :health-insurance-id :accessor health-insurance-id)
   (visit-id :col-name visitId :col-type integer
	     :initarg :visit-id :accessor visit-id)
   (bill-id :col-name billId :col-type integer :col-references ((bills id))
	    :initarg :bill-id :accessor bill-id)
   (n-pends :accessor n-pends)
   (n-open-pends :accessor n-open-pends)
   (n-docs :accessor n-docs)
   (n-not-received-docs :accessor n-not-received-docs)
   (n-checlist-item :accessor n-checlist-item)
   (n-done-checlist-item :accessor n-done-checlist-item))
  (:metaclass dao-class)
  (:keys id)
  (:table-name cards))

(defclass health-insurance ()
  ((id :col-type integer :col-identity t :accessor id)
   (name :col-type string :check (:<> 'name "")
	  :initarg :name :accessor name))
  (:metaclass dao-class)
  (:keys id)
  (:table-name healthInsurances))

(defclass patient ()
  ((id :col-type integer :col-identity t :accessor id)
   (name :col-type string :check (:<> 'name "")
	  :initarg :name :accessor name))
  (:metaclass dao-class)
  (:keys id)
  (:table-name patients))

(defclass bill ()
  ((id :col-type integer :col-identity t :accessor id)
   (type-id :col-name typeId :col-type integer :col-references ((billTypes id))
	       :initarg :type-id :accessor type-id)
   (total-amount :col-name totalAmount :col-type float
		 :initarg :total-amount :accessor total-amount)
   (type-name :accessor type-name))
  (:metaclass dao-class)
  (:keys id)
  (:table-name bills))

(defclass bill-type ()
  ((id :col-type integer :col-identity t :accessor id)
   (name :col-type string :check (:<> 'name "")
	 :initarg :name :accessor name))
  (:metaclass dao-class)
  (:keys id)
  (:table-name billTypes))

(defclass cards-pendencies ()
  ((card-id :col-name cardId :col-type integer :col-references ((cards id))
	       :initarg :card-id :accessor card-id)
   (pendency-id :col-name pendencyID :col-type integer :col-references ((pendecies id))
	       :initarg :pendency-id :accessor pendency-id))
  (:metaclass dao-class)
  (:keys id)
  (:table-name cardsPendencies))

(defclass cards-documents ()
  ((card-id :col-name cardId :col-type integer :col-references ((cards id))
	       :initarg :card-id :accessor card-id)
   (document-id :col-name documentID :col-type integer :col-references ((documents id))
	       :initarg :document-id :accessor document-id))
  (:metaclass dao-class)
  (:keys id)
  (:table-name cardsDocuments))

(defclass cards-checklist-item ()
  ((card-id :col-name cardId :col-type integer :col-references ((cards id))
	       :initarg :card-id :accessor card-id)
   (checklist-item-id :col-name checklistItemID :col-type integer :col-references ((checklistItems id))
	       :initarg :checklist-item-id :accessor checklist-item-id))
  (:metaclass dao-class)
  (:keys id)
  (:table-name cardsChecklistItem))

(defclass pendency ()
  ((id :col-type integer :col-identity t :accessor id)
   (openp :col-name open :col-type boolean :initarg :openp :accessor openp))
  (:metaclass dao-class)
  (:keys id)
  (:table-name pendencies))

(defclass documents ()
  ((id :col-type integer :col-identity t :accessor id)
   (not-receivedp :col-name notReceived :col-type boolean :initarg :not-receivedp :accessor not-receivedp))
  (:metaclass dao-class)
  (:keys id)
  (:table-name pendencies))

(defclass checklist-item ()
  ((id :col-type integer :col-identity t :accessor id)
   (donep :col-name done :col-type boolean :initarg :donep :accessor donep))
  (:metaclass dao-class)
  (:keys id)
  (:table-name checklistItems))

(defmacro defjson (class &body definitions)
  (let ((object (gensym)))
    `(defmethod %to-json ((,object ,class))
       (with-slots ,(mapcar #'second definitions) ,object
	 (with-object
	   ,@(mapcar #'(lambda (definition)
			 `(write-key-value ,(first definition)
					   ,(second definition)))
		     definitions))))))

(defjson activity
  ("activityId" id)
  ("activityTitle" title)
  ("activitySubtitle" subtitle)
  ("sla" sla))

(defjson patient
  ("patientId" id)
  ("name" name))

(defjson health-insurance
  ("healthInsuranceId" id)
  ("name" name))
